Question 1: Create a NumPy array with 5 elements initialized with zeros.
"""

import numpy as np
array = np.zeros(5)
print(array)

"""Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones."""

import numpy as np
array = np.ones((3, 4))
print(array)

"""Question 3: Create a 1D NumPy array containing numbers from 1 to 10."""

import numpy as np
array = np.arange(1, 11)
print(array)

"""Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9."""

import numpy as np
array = np.arange(1, 10).reshape(3, 3)
print(array)

"""Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9."""

import numpy as np
array = np.random.randint(0, 10, size=(2, 3, 4))
print(array)

"""Question 6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5]."""

import numpy as np
list_data = [1, 2, 3, 4, 5]
array = np.array(list_data)
print(array)

"""Question 7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array."""

import numpy as np
tuple_data = (6, 7, 8, 9, 10)
array = np.array(tuple_data)
print(array)

"""Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7."""

import numpy as np
array = np.arange(8).reshape(4, 2)
print(array)

"""Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros."""

import numpy as np
array = np.zeros((2, 3, 4))
print(array)

"""Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1."""

import numpy as np
array = np.random.rand(3, 3)
print(array)

"""Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5.

"""

import numpy as np
array = np.arange(10, 51, 5)
print(array)

"""Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7."""

import numpy as np
array = np.linspace(-2, 7, 10).reshape(2, 5)
print(array)

"""Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.

"""

import numpy as np
array = np.arange(100, 110)
array_float = array.astype(float)
print(array_float)

"""Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int."""

import numpy as np
array = np.ones((3, 4))
array_int = array.astype(int)
print(array_int)

"""Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]]."""

import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(array)

Question 1: Create a NumPy array with 5 elements initialized with zeros.

In [3]:
import numpy as np
array=np.zeros(5,dtype=int)
print(array)

[0 0 0 0 0]


Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones.

In [6]:
import numpy as np
array=np.ones((3,4),dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Question 3: Create a 1D NumPy array containing numbers from 1 to 10.

In [8]:
import numpy as np
array=np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9.

In [10]:
import numpy as np
array=np.arange(1,10).reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9.

In [15]:
import numpy as np
array=np.random.randint(0,10,size=(2,3,4))
array

array([[[3, 6, 1, 3],
        [8, 5, 9, 4],
        [0, 5, 9, 5]],

       [[6, 4, 0, 5],
        [8, 6, 7, 9],
        [8, 8, 8, 0]]])

Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7

In [16]:
import numpy as np
array=np.arange(8).reshape(4,2)
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros

In [17]:
import numpy as np
array=np.zeros((2,3,4))
array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1.

In [18]:
import numpy as np
array=np.random.rand(3,3)
array

array([[0.67988291, 0.0682959 , 0.08404101],
       [0.53628981, 0.9909207 , 0.91648044],
       [0.57708747, 0.7339483 , 0.38227199]])

Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5

In [19]:
import numpy as np
array=np.arange(10,51,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7.

In [20]:
import numpy as np
array=np.linspace(-2,7,10).reshape(2,5)
print(array)

[[-2. -1.  0.  1.  2.]
 [ 3.  4.  5.  6.  7.]]


Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float

In [ ]:
import numpy as np
array=np.arange((100,110),dtype=float)
array_float=array.astype(float)
print(array_float)

Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int.

In [22]:
import numpy as np
array=np.ones((3,4),dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]]

In [ ]:
import numpy as np
array=np.arrange(1,13).reshape(2,2,3)
print(array)